name: run python test

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest
steps: 
- used: action/checkout@v2
- name: install Python 3
uses: 
with: action/setup-python@v1
- name : Install Dependencies
run: python -m pip install --upgrade pip
pip install -r requirements.txt


