name: Pull latest changes and deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted,Linux,X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull latest changes
      run: |
        cd /var/www/NGINX/
        git pull origin main
